name: 'hypersl'
log_name: 'hypersl-clf'
loss_name: 'cross_entropy'
learning_rate: 1e-4
optimizer_name: 'AdamW'
optimizer_eps: 1e-08
momentum: 0.0
weight_decay: 1e-4
export_preds_every_n_epochs: null
bb_model_size: 'small'
bb_weights_file: './modelweights/hypersl_backbone/5_base_mask95_checkpoint.pt'
plot_batch: False
sub_batch_size: 8192
class_weighting: null
freeze_backbone: False
use_backbone: False
mlp_classifier: False